myportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

admin.site.site_header = "NinjaRoot Administration"
admin.site.site_title = "NinjarootDev"
admin.site.index_title = "Bienvenue Admin"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/models.py
from django.db import models


class Contactus(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
 
    class Meta:
        verbose_name_plural = "Contactus"
 
    def __str__(self):
        return self.last_name + "-" +  self.email


class Work(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='myworks/')
    body = models.TextField()
    link = models.CharField(max_length=200)
    
    def str(self):
        return self.title


class Dcoder(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='myworks/')
    body = models.TextField()
    local = models.CharField(max_length=100)
    whatsapp = models.CharField(max_length=200)
    facebook = models.CharField(max_length=200)
    twitter = models.CharField(max_length=200)
    instagram = models.CharField(max_length=200)
    linkedin = models.CharField(max_length=200)
    github = models.CharField(max_length=200)
        
    def str(self):
        return self.name


class Aboutme(models.Model):
    image = models.ImageField(upload_to='myworks/')
    body = models.TextField()
    whatsapp = models.CharField(max_length=200)
    facebook = models.CharField(max_length=200)
    twitter = models.CharField(max_length=200)
    instagram = models.CharField(max_length=200)
    linkedin = models.CharField(max_length=200)
    github = models.CharField(max_length=200)
            

class Prog(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
            
    def str(self):
        return self.title

CATEGORY_CHOICES = (
    ('D', 'design'),
    ('W', 'web'),
    ('B', 'brand')
)

class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery/')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
            
    def str(self):
        return self.category        
            
class Myimgacceuil(models.Model):
    image = models.ImageField(upload_to='myimghome/')

portfolio/forms.py
from django import forms
from .models import *


class ContactusForm(forms.ModelForm):
    class Meta:
        model = Contactus
        fields = '__all__'
        

portfolio/views.py
from django.core.mail import send_mail, BadHeaderError, mail_admins
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from .models import *
from django.contrib import messages


def index(request):
    if request.method == 'POST':
        f = ContactusForm(request.POST)
        if f.is_valid():
            first_name = f.cleaned_data['first_name']
            last_name = f.cleaned_data['last_name']
            sender = f.cleaned_data['email']
            subject = "You have a new message from {}:{}".format(last_name, sender)
            message = "Subject: {}\n\nMessage: {}".format(f.cleaned_data['subject'], f.cleaned_data['message'])
            mail_admins(subject, message)

            f.save()
            messages.add_message(request, messages.INFO, 'votre message a été envoyer avec success.')
            return redirect('contact')
    else:
        f = ContactusForm()
    context = {
        'imgas': Myimgacceuil.objects.all(),
        'abouts': Aboutme.objects.all(),
        'works': Work.objects.all(),
        'dcoder': Dcoder.objects.all(),
        'gallerys': Gallery.objects.all(),
        'progs': Prog.objects.all(),
    }
    return render(request, 'portfolio/index.html',context)

portfolio/templates/portfolio/about.html
{% load static %}

{% for about in abouts %}

<div class="site-section" id="about-section">
<div class="container">
    <div class="row align-items-center">
    <div class="col-lg-6 mb-5">
        <img src="{{about.image.url}}" alt="Image" class="img-fluid">
    </div>
    <div class="col-lg-5 ml-auto section-title">
        <span class="sub-title mb-2 d-block">Acquaint me</span>
        <h2 class="title text-primary mb-3">About me</h2>
        <p class="mb-4">{{about.body}}</p>


        <div class="d-flex">
        <ul class="list-unstyled ul-check success mr-5">
            <li>Design</li>
            <li>Development</li>
            <li>eCommerce</li>
                
        </ul>
        <ul class="list-unstyled ul-check success">
                
            <li>Mobile Apps</li>
            <li>Copywriting</li>
            <li>SEO</li>
        </ul>
        </div>
        <p class="d-flex align-items-center">
            <span class="mr-3 text-black">Follow me:</span>
            <a href="{{about.whatsapp}}" class="whatsapp p-2"><span class="icon-whatsapp" style="color: green"></span></a>
            <a href="{{about.facebook}}" class="facebook p-2"><span class="icon-facebook"></span></a>
            <a href="{{about.twitter}}" class="twitter pr-2 pt-2 pb-2 pl-0"><span class="icon-twitter"></span></a>
            <a href="{{about.instagram}}" class="instagram p-2"><span class="icon-instagram"></span></a>
            <a href="{{about.linkedin}}" class="linkedin p-2"><span class="icon-linkedin"></span></a>
            <a href="{{about.github}}" class="github p-2"><span class="icon-github"></span></a>
        </p>
    </div>
    </div>
</div>
</div> <!-- .END site-section -->
{% endfor %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include "portfolio/header.html" %}

<title>{% block titled %}{% endblock titled %}</title>
{% block extra_head %} {% endblock %}


<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
{% include "portfolio/nav.html"%}
{% if messages %} 
<div class="mt-0" style="height: 200px;">
{% for message in messages %}
<div
    class="alert alert-{{ message.tags }} alert-dismissible fade show"
    role="alert"
>
    {{ message }}

    <button
    type="button"
    class="close"
    data-dismiss="alert"
        aria-label="Close"
        >
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
        {% endfor %} 
    </div>
    {% endif %} 


    {% block content %} 
    {% endblock content %}

    {% block extra_body %} 
    {% endblock %} 

    {% include "portfolio/footer.html"%} 
    {% include "portfolio/script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

portfolio/templates/portfolio/contact.html
<div class="site-section" id="contact-section">
<div class="container">
    <form class="contact-form" action="." method="post" id="contactForm" novalidate="novalidate">
    {% csrf_token %}
    <div class="section-title text-center mb-5">
        <span class="sub-title mb-2 d-block">Get In Touch</span>
        <h2 class="title text-primary">Contact me</h2>
    </div>

    <div class="row mb-4">
        <div class="col-md-6 mb-4 mb-md-0">
        <input type="text" class="form-control" placeholder="First name" name="first_name" id="id_first_name">
        </div>
        <div class="col-md-6">
        <input type="text" class="form-control" placeholder="Last name" name="last_name" id="id_last_name">
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-6 mb-4 mb-md-0">
        <input type="email" class="form-control" placeholder="Email" name="email" id="id_email">
        </div>

        <div class="col-6">
        <input type="Subject" class="form-control" placeholder="Subject" name="subject" id="id_subject">
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
        <textarea class="form-control" name="message" id="id_message" cols="30" rows="10" placeholder="Message"></textarea>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
        <button type="submit" class="btn btn-primary btn-md">Send Message</button>
        </div>
    </div>

    </form>
</div>
</div> 

portfolio/templates/portfolio/dcoder.html
{% load static %}

{% for dcoder in decoders %}
<div class="site-section" id="what-we-do-section">
<div class="container">
    <div class="row mb-5">
    <div class="col-lg-6 section-title">
        <span class="sub-title mb-2 d-block">Meet my Team</span>
        <h2 class="title text-primary">We are talented people.</h2>
    </div>
    </div>
    <div class="row no-gutters">
    <div class="col-lg-12 person">
        <img src="{{dcoder.logo.url}}" alt="Image" class="img-fluid mb-5" style="width: 100%">
        <div class="row">
        <div class="col-lg-10 ml-auto">
            <div class="pr-lg-5">
            <h3>{{dcoder.name}}</h3>
            <span class="mb-4 d-block">{{dcoder.local}}</span>
            <p>{{dcoder.body}}</p>
            <p class="d-flex align-items-center">
                <span class="mr-3 text-black">Follow us:</span>
                <a href="{{dcoder.whatsapp}}" class="whatsapp p-2"><span class="icon-whatsapp" style="color: green"></span></a>
                <a href="{{dcoder.facebook}}" class="facebook p-2"><span class="icon-facebook"></span></a>
                <a href="{{dcoder.twitter}}" class="twitter pr-2 pt-2 pb-2 pl-0"><span class="icon-twitter"></span></a>
                <a href="{{dcoder.instagram}}" class="instagram p-2"><span class="icon-instagram"></span></a>
                <a href="{{dcoder.linkedin}}" class="linkedin p-2"><span class="icon-linkedin"></span></a>
                <a href="{{dcoder.github}}" class="github p-2"><span class="icon-github"></span></a>
            </p>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
</div>
{% endfor %}

portfolio/templates/portfolio/fadmin.html
<h1>On dirait que vous etre perdus</h1>

portfolio/templates/portfolio/footer.html
<footer class="site-footer">
    <div class="container">
        <div class="row">
        <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
            <div class="col-12">
                <h3 class="footer-heading mb-4">About me</h3>
                {% for about in abouts %}
                <p>{{about.body}}</p>
                {% endfor %}
            </div>
            </div>
            

            
        </div>
        <div class="col-lg-3 ml-auto">
           
            <div class="row mb-5">
            <div class="col-md-12">
                <h3 class="footer-heading mb-4">links</h3>
            </div>
            <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                <li><a href="#home-section" class="smoothscroll">Home</a></li>
                <li><a href="#what-i-do-section" class="smoothscroll">What I Do</a></li>
                <li><a href="#about-section" class="smoothscroll">About me</a></li>
                <li><a href="#team-section"  class="smoothscroll">My Team</a></li>
                </ul>
            </div>
              
            </div>
            
        </div>
          

        <div class="col-lg-4 mb-5 mb-lg-0">

            <div class="mb-5">
            <h3 class="footer-heading mb-2">Subscribe Newsletter</h3>
            <p>Subscribe to my portfolio</p>

            <form method="post" class="form-subscribe">
                <div class="form-group mb-3">
                <input type="text" class="form-control border-white text-white bg-transparent" placeholder="Enter full name" aria-label="Enter Email" aria-describedby="button-addon2">
                </div>
                <div class="form-group mb-3">
                <input type="text" class="form-control border-white text-white bg-transparent" placeholder="Enter email" aria-label="Enter Email" aria-describedby="button-addon2">
                </div>
                <div class="form-group">
                <button class="btn btn-primary px-5" type="submit">Subscribe</button>
                </div>
            </form>

            </div>

            


        </div>
          
        </div>
        <div class="row pt-5 mt-5 text-center">
        <div class="col-md-12">
            {% for about in abouts %}
            <div class="mb-4">
                <a href="{{about.whatsapp}}" class="pl-0 pr-3"><span class="icon-whatsapp" style="color: green"></span></a>
                <a href="{{about.facebook}}" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                <a href="{{about.twitter}}" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                <a href="{{about.instagram}}" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                <a href="{{about.linkedin}}" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
                <a href="{{about.github}}" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
                </div>
            <p>
            {% endfor %}
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | NinjaRoot <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="#about-section">Castin Stanley</a>
            </p>
        </div>
          
        </div>
    </div>
    </footer>
</div>

portfolio/templates/portfolio/gallery.html
{% load static %}


<div class="site-section" id="gallery-section">
<div class="container">

    <div class="row mb-5 ">
    <div class="col-md-7 section-title text-center mx-auto">
        <span class="sub-title mb-2 d-block">Photos</span>
        <h2 class="title text-primary mb-3">Works Gallery</h2>
    </div>
    </div>
       
    <div id="posts" class="row no-gutter">
    {% for gallery in gallerys %}
    <div class="item {{gallery.get_category_display}} col-6 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-4">
        <a href="{{gallery.image.url}}" class="item-wrap" data-fancybox="gal">
        <span class="icon-search2"></span>
        <img class="img-fluid" src="{{gallery.image.url}}">
        </a>
    </div>
    {% endfor %}

    </div>
</div>
</div> <!-- END .site-section -->

portfolio/templates/portfolio/header.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap-datepicker.css' %}">
    
    
    <link rel="stylesheet" href="{% static 'portfolio/fonts/flaticon/font/flaticon.css' %}">
  
    <link rel="stylesheet" href="{% static 'portfolio/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/jquery.fancybox.min.css' %}">
    

    <link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
    
</head>

portfolio/templates/portfolio/index.html
    {% extends 'portfolio/base.html' %}
    {% block titled %}NinjarootDev &mdash; Portfolio{% endblock titled %}
    {% load static %}

    {% block content %}

    
    <div class="site-blocks-cover" id="home-section">
      <div class="img-wrap">
        <div class="owl-carousel slide-one-item hero-slider">
          <div class="slide">
            <img src="images/glint_hero_1.jpg" alt="Image">  
          </div>
          <div class="slide">
            <img src="images/glint_hero_2.jpg" alt="Image">  
          </div>
          <div class="slide">
            <img src="images/glint_hero_3.jpg" alt="Image">  
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto align-self-center">
            <div class="intro">
              <div class="heading">
                <h1 style="color: blue">Ninja<span style="color: red">Root</span></h1>
              </div>
              <div class="text">
                <p class="sub-text mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde modi blanditiis iure.</p>
                <p><a href="#" target="_blank" class="btn btn-outline-primary btn-md">See my <b>Github projects</b></a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- END .site-blocks-cover -->
    
{% include "portfolio/progs.html"%} 
{% include "portfolio/about.html"%} 
{% include "portfolio/dcoder.html"%} 
{% include "portfolio/works.html"%} 
{% include "portfolio/gallery.html"%} 
{% include "portfolio/contact.html"%} 

  



   {% endblock %}

portfolio/templates/portfolio/nav.html
<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
        <span class="icon-close2 js-menu-toggle"></span>
        </div>
    </div>
    <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->


    <div class="site-navbar-wrap">

    <div class="site-navbar site-navbar-target js-sticky-header">
        <div class="container">
        <div class="row align-items-center">
            <div class="col-6 col-md-4">
            <h1 class="my-0 site-logo"><a href="/" style="color: blue">Ninja<span class="text-primary">Root</span>. </a></h1>
            </div>
            <div class="col-6 col-md-8">
            <nav class="site-navigation text-right" role="navigation">
                <div class="container">

                <div class="d-inline-block d-lg-block ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-black">
                    <span class="icon-menu h3"></span> <span class="menu-text">Menu</span>
                </a></div>

                <ul class="site-menu main-menu js-clone-nav d-none d-lg-none">
                    <li><a href="#home-section" class="nav-link">Home</a></li>
                    <li><a href="#what-i-do-section" class="nav-link">What i Do</a></li>
                    <li><a href="#about-section" class="nav-link">About me</a></li>
                    <li><a href="#portfolio-section" class="nav-link">Portfolio</a></li>
                    <li><a href="#works-gallery-section" class="nav-link">Works Gallery</a></li>
                    <li><a href="#contact-section" class="nav-link">Contact me</a></li>
                </ul>
                </div>
            </nav>
            </div>
        </div>
        </div>
    </div>
    </div> <!-- END .site-navbar-wrap -->

portfolio/templates/portfolio/progs.html
<div class="site-section" id="what-i-do-section">
<div class="container">
    <div class="row mb-5">
    <div class="col-lg-6 section-title">
        <span class="sub-title mb-2 d-block">What I Do</span>
        <h2 class="title text-primary">Far far away, behind the word mountains far from the countries</h2>
    </div>
    </div>
    <div class="row">
    <div class="col-lg-10 ml-auto">
        <div class="row">
        {% for prog in progs %}
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                <div class="service h-100">
                <h3>{{porg.title}}</h3>
                <p>{{porg.body}}</p>
                <p><a href="#portfolio-section" class="readmore">Learn more</a></p>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    </div>
</div>
</div> <!-- END .site-section -->

portfolio/templates/portfolio/script.html
{% load static %}

<script src="{% static 'portfolio/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'portfolio/js/popper.min.js' %}"></script>
<script src="{% static 'portfolio/js/bootstrap.min.js' %}"></script>
<script src="{% static 'portfolio/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'portfolio/js/aos.js' %}"></script>
<script src="{% static 'portfolio/js/jquery.sticky.js' %}"></script>
<script src="{% static 'portfolio/js/stickyfill.min.js' %}"></script>
<script src="{% static 'portfolio/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'portfolio/js/isotope.pkgd.min.js' %}"></script>
  
<script src="{% static 'portfolio/js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'portfolio/js/main.js' %}"></script>

portfolio/templates/portfolio/works.html
{% load static %}

<div class="site-section" id="portfolio-section">
<div class="container">
    <div class="row mb-5 ">
    <div class="col-md-7 section-title text-center mx-auto">
        <span class="sub-title mb-2 d-block">Recent Works</span>
        <h2 class="title text-primary mb-3">I love what i do, check out some of my latest works</h2>
    </div>
    </div>
    
    {% for work in works %}
    <div class="row mb-5">
    <div class="col-lg-6 order-1 order-lg-2 mb-4 mb-lg-0">
        <img src="{{work.image.url}}" alt="Image" class="img-fluid">
    </div>
    <div class="col-lg-5 h-100 jm-sticky-top mr-auto order-2 order-lg-1">
        <h3>{{work.title}}</h3>
        <p class="mb-4">{{work.body}}</p>
        <p class="mb-4"><a href="{{work.link}}" class="readmore">Visit website</a></p>
    </div>
    </div>
    {% endfor %}

</div>
</div>